# pubspec.yaml (updated)
name: FocusMate
description: "FocusMate - A professional productivity timer app with focus tracking and task synchronization"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_animate: ^4.2.0
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  uuid: ^4.5.1
  lottie: ^2.6.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.3.0
  material_symbols_icons: ^4.2811.0
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  sqlite3_flutter_libs: ^0.5.20
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  adaptive_icon_background: "#3F51B5"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/